#!/bin/bash
# ============================================================
# SourceChain — Deploy Script for GenLayer Testnet
# ============================================================
# Prerequisites:
#   - GenLayer CLI installed: pip install genlayer
#   - Account configured: genlayer accounts create
#   - Testnet RPC accessible
# ============================================================

set -e  # Exit on any error

echo "╔══════════════════════════════════════════════════════╗"
echo "║         SourceChain — GenLayer Deploy Script         ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""

# ── Configuration ─────────────────────────────────────────
NETWORK="${NETWORK:-testnet_asimov}"
CONTRACTS_DIR="$(dirname "$0")/../contracts"
RPC_URL="${RPC_URL:-https://studio.genlayer.com/api}"

echo "📡 Network:  $NETWORK"
echo "📂 Contracts: $CONTRACTS_DIR"
echo "🔗 RPC:      $RPC_URL"
echo ""

# ── Step 1: Validate contract files exist ─────────────────
echo "🔍 Step 1: Validating contract files..."
if [ ! -f "$CONTRACTS_DIR/SourceChainTreasury.py" ]; then
    echo "❌ ERROR: SourceChainTreasury.py not found in $CONTRACTS_DIR"
    exit 1
fi
if [ ! -f "$CONTRACTS_DIR/SourceChainRegistry.py" ]; then
    echo "❌ ERROR: SourceChainRegistry.py not found in $CONTRACTS_DIR"
    exit 1
fi

# ── Step 2: Validate header compliance ────────────────────
echo "🔍 Step 2: Checking GenLayer header compliance..."
for contract in SourceChainTreasury.py SourceChainRegistry.py; do
    first_line=$(head -1 "$CONTRACTS_DIR/$contract")
    if [ "$first_line" != "# v0.2.16" ]; then
        echo "❌ ERROR: $contract must start with '# v0.2.16' (found: '$first_line')"
        exit 1
    fi
    echo "  ✅ $contract header OK"
done

# ── Step 3: Deploy SourceChainTreasury first ──────────────
echo ""
echo "🚀 Step 3: Deploying SourceChainTreasury.py..."
echo "   (Treasury must be deployed before Registry)"
echo ""
echo "   MANUAL STEP REQUIRED:"
echo "   ┌──────────────────────────────────────────────────────┐"
echo "   │ 1. Open https://studio.genlayer.com                  │"
echo "   │ 2. Settings → Reset Storage → Confirm               │"
echo "   │ 3. Hard refresh (Ctrl+Shift+F5)                      │"
echo "   │ 4. Upload: contracts/SourceChainTreasury.py          │"
echo "   │ 5. Constructor args:                                  │"
echo "   │    - registry_address: \"0x0\" (placeholder for now)   │"
echo "   │    - submission_fee: 1000000                         │"
echo "   │    - slash_percentage: 50                            │"
echo "   │ 6. Click Deploy                                       │"
echo "   │ 7. Wait for tx → verify Result: SUCCESS (not ERROR)  │"
echo "   │ 8. Copy the contract address                         │"
echo "   └──────────────────────────────────────────────────────┘"
echo ""
read -p "📋 Paste Treasury contract address: " TREASURY_ADDRESS

if [ -z "$TREASURY_ADDRESS" ]; then
    echo "❌ ERROR: Treasury address cannot be empty"
    exit 1
fi

echo "  ✅ Treasury address: $TREASURY_ADDRESS"

# ── Step 4: Deploy SourceChainRegistry ────────────────────
echo ""
echo "🚀 Step 4: Deploying SourceChainRegistry.py..."
echo ""
echo "   MANUAL STEP REQUIRED:"
echo "   ┌──────────────────────────────────────────────────────┐"
echo "   │ 1. Upload: contracts/SourceChainRegistry.py          │"
echo "   │ 2. Constructor args:                                  │"
echo "   │    - treasury_address: \"$TREASURY_ADDRESS\"           │"
echo "   │    - admin_address: \"<your-wallet-address>\"          │"
echo "   │ 3. Click Deploy                                       │"
echo "   │ 4. Wait for tx → verify Result: SUCCESS (not ERROR)  │"
echo "   │ 5. Copy the contract address                         │"
echo "   └──────────────────────────────────────────────────────┘"
echo ""
read -p "📋 Paste Registry contract address: " REGISTRY_ADDRESS

if [ -z "$REGISTRY_ADDRESS" ]; then
    echo "❌ ERROR: Registry address cannot be empty"
    exit 1
fi

echo "  ✅ Registry address: $REGISTRY_ADDRESS"

# ── Step 5: Save addresses to .env ─────────────────────────
echo ""
echo "💾 Step 5: Saving contract addresses..."
FRONTEND_ENV="../frontend/.env.local"

cat > "$FRONTEND_ENV" << EOF
# SourceChain Contract Addresses — Auto-generated by deploy.sh
# Network: $NETWORK
# Deployed: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

NEXT_PUBLIC_REGISTRY_ADDRESS=$REGISTRY_ADDRESS
NEXT_PUBLIC_TREASURY_ADDRESS=$TREASURY_ADDRESS
NEXT_PUBLIC_NETWORK=$NETWORK
NEXT_PUBLIC_RPC_URL=$RPC_URL
EOF

echo "  ✅ Addresses saved to: $FRONTEND_ENV"

# ── Step 6: Smoke-test via Studio UI ──────────────────────
echo ""
echo "🧪 Step 6: Smoke test instructions..."
echo "   ┌──────────────────────────────────────────────────────┐"
echo "   │ 1. In Studio, select SourceChainRegistry             │"
echo "   │ 2. Call submit_article() with:                       │"
echo "   │    - article_id: \"test-001\"                          │"
echo "   │    - article_hash: \"sha256:test123abc\"               │"
echo "   │    - article_title: \"Test Article\"                   │"
echo "   │    - article_text: (at least 50 chars of text)       │"
echo "   │    - source_urls: '[\"https://example.com\"]'         │"
echo "   │    - author_address: \"<your-wallet>\"                 │"
echo "   │ 3. Call get_article_status(\"test-001\")               │"
echo "   │    → Should return \"PENDING\"                         │"
echo "   │ 4. Call verify_article(\"test-001\")                   │"
echo "   │    → Wait 30-90s for AI consensus                    │"
echo "   │    → Should return \"VERIFIED\" or \"REJECTED\"          │"
echo "   │ 5. Verify Result: SUCCESS in tx sidebar              │"
echo "   └──────────────────────────────────────────────────────┘"
echo ""

# ── Summary ───────────────────────────────────────────────
echo "╔══════════════════════════════════════════════════════╗"
echo "║                 DEPLOY COMPLETE ✅                   ║"
echo "╠══════════════════════════════════════════════════════╣"
echo "║  Treasury:  $TREASURY_ADDRESS"
echo "║  Registry:  $REGISTRY_ADDRESS"
echo "║  Network:   $NETWORK"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
echo "🌐 Next steps:"
echo "   cd frontend && npm run dev"
echo "   → Open http://localhost:3000"
echo ""
echo "📚 Deploy docs: README.md#deploy-to-testnet"
